In [1]:
import pandas as pd
from pycaret.classification import *

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data', header=None)
df.columns = ['id', 'diagnosis', 'mean_radius', 'mean_texture', 'mean_perimeter', 'mean_area', 'mean_smoothness', 'mean_compactness', 'mean_concavity', 'mean_concave_points', 'mean_symmetry', 'mean_fractal_dimension', 'se_radius', 'se_texture', 'se_perimeter', 'se_area', 'se_smoothness', 'se_compactness', 'se_concavity', 'se_concave_points', 'se_symmetry', 'se_fractal_dimension', 'worst_radius', 'worst_texture', 'worst_perimeter', 'worst_area', 'worst_smoothness', 'worst_compactness', 'worst_concavity', 'worst_concave_points', 'worst_symmetry', 'worst_fractal_dimension']
df.drop(['id'], axis=1, inplace=True)

In [2]:
clf = setup(data=df, target='diagnosis', train_size=0.7, log_experiment=True, log_plots=True, experiment_name='Breast_Cancer')

In [3]:
best_model = compare_models(fold=5, sort='F1')

In [4]:
tuned_model = tune_model(best_model, optimize='F1', n_iter=50, search_library='optuna')

[I 2023-04-20 05:00:56,666] Searching the best hyperparameters using 398 samples...
[I 2023-04-20 05:31:45,745] Finished hyperparemeter search!

In [5]:
ensemble_model = ensemble_model(tuned_model, fold=5, method='Bagging')

In [2]:
predictions = predict_model(ensemble_model, data=test_data)

NameError: name 'predict_model' is not defined